---
- name: testing playbook
  hosts: windows
  gather_facts: yes
  tasks:
  - name: display hostname
    debug: msg="{{ ansible_hostname }}"

  - name: test for file
    win_wait_for:
      path: c:\temp\{{ ansible_hostname }}.txt
      timeout: 5
    ignore_errors: true
    register: file_found

  - name: display file found status
    debug: msg="{{ file_found.failed }}"

  - name: get file results and process
    block:
      - name: get file contents
        win_shell: |
          Get-Content 'c:\temp\{{ ansible_hostname }}.txt'
        register: ts_result

      - name: display ts_result
        debug: msg="{{ ts_result.stdout_lines[0] }}"

      - name: display success message
        debug: msg="task seq passed!!!"
        when: ts_result.stdout_lines[0] == "passed"

      - name: display failed message
        debug: msg="task seq failed!!!"
        when: ts_result.stdout_lines[0] == "failed"

    when: file_found.failed == false

  - name: display timed out
    debug: msg="timed out!!!"
    when: file_found.failed == true
